// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6feJNkzj_29MoqARAekmTlCxth3OsvlY',
    appId: '1:1094664005169:web:41b0bd33630f1206c25710',
    messagingSenderId: '1094664005169',
    projectId: 'udemy-course-ce7b6',
    authDomain: 'udemy-course-ce7b6.firebaseapp.com',
    storageBucket: 'udemy-course-ce7b6.appspot.com',
    measurementId: 'G-PKF4609H7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGM0uIAJ5hFx6goq-etxVkhMPfJFwwIn8',
    appId: '1:1094664005169:android:752c2243a3bb4791c25710',
    messagingSenderId: '1094664005169',
    projectId: 'udemy-course-ce7b6',
    storageBucket: 'udemy-course-ce7b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhQKJ9rwgPWMUOvkGqp7nSJKS1KwkrqBw',
    appId: '1:1094664005169:ios:8ba9d045548077a6c25710',
    messagingSenderId: '1094664005169',
    projectId: 'udemy-course-ce7b6',
    storageBucket: 'udemy-course-ce7b6.appspot.com',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhQKJ9rwgPWMUOvkGqp7nSJKS1KwkrqBw',
    appId: '1:1094664005169:ios:fb5e47fad8dd8e9fc25710',
    messagingSenderId: '1094664005169',
    projectId: 'udemy-course-ce7b6',
    storageBucket: 'udemy-course-ce7b6.appspot.com',
    iosBundleId: 'com.example.src.RunnerTests',
  );
}
